name: Java CI with Maven - External Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
   uses: gsorrent/spring-boot-web/.github/workflows/build_reuse.yml@master

  deploy:
   runs-on: ubuntu-latest
   needs: build

   steps:       
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up the Maven dependencies caching
      uses: actions/cache@v3.3.2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_simplilearn:1.0
    - name: build image 
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app_simplilearn:1.0 .
    - name: push image 
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/app_simplilearn:1.0
