name: Java CI with Maven - External Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
   uses: gsorrent/spring-boot-web/.github/workflows/build_reuse.yml@master

  deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Build and push
     uses: docker/build-push-action@v5
     with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_simplilearn:1.0
   - name: build image 
     run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app_simplilearn:1.0 .
   - name: push image 
     run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/app_simplilearn:1.0
