name: Java CI with Maven - External Workflow
on:
  push:
    branches: [ "master" ]
    paths:
      -  'src/**'
      - '.github/workflows/maven.yaml'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
   uses: gsorrent/spring-boot-web/.github/workflows/build_reuse.yml@master
      
